### ISSUE TITLE
XMLLexiconTest Fails on Master

### ISSUE THREAD

**Issue by ghost** [rali-udem/SimpleNLG-EnFr#1]
Hello,

I want to make a change to the XMLLexicon, but the Junits are failing for me on master.  Are you seeing this as well, or is it a problem with my build.

```
Loading XML lexicon took 699 ms

junit.framework.ComparisonFailure: 
Expected :eat
Actual   :eating
 <Click to see difference>
    at simplenlg.test.SharedLexiconTests.doBasicTests(SharedLexiconTests.java:110)
    at simplenlg.test.XMLLexiconTest.testBasics(XMLLexiconTest.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)


Process finished with exit code 255
```

**Comment by vaudrypl** [comment]
Hi,

Since the first release of SimpleNLG-EnFr, this test (and only this one) was specified not to pass. (It's mentioned in docs/modifications.txt ) All the original tests of SimpleNLG were left unmodified in the test package, while the packages test.english and test.french were added to test SimpleNLG-EnFr itself.

In short, you can expect test.XMLLexiconTest to fail, but test.english.XMLLexiconTest and test.french.XMLLexiconTest should succeed.

I hope that clears things up.
